import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, relative, resolve } from 'node:path'
import type { ProcConfig } from './types.js'
import type { ColumnDef, ColumnType, TempTableDef } from '../../src/types.js'
import { loadRawDefs } from './loader.js'

// ---------------------------------------------------------------------------
// Type name helpers
// ---------------------------------------------------------------------------

function toPascalCase(name: string): string {
  return name
    .split('_')
    .map((w) => (w.length > 0 ? w[0]!.toUpperCase() + w.slice(1) : ''))
    .join('')
}

function procNameToTypeName(procName: string): string {
  return `DBProc${toPascalCase(procName)}`
}

// ---------------------------------------------------------------------------
// ColumnDef → TypeScript type string (runtime equivalent of ColumnDefToTs)
// ---------------------------------------------------------------------------

function columnTypeToTs(type: ColumnType): string {
  switch (type) {
    case 'uuid':
    case 'text':
    case 'varchar':
      return 'string'
    case 'integer':
    case 'smallint':
    case 'bigint':
    case 'numeric':
    case 'decimal':
    case 'real':
    case 'float':
      return 'number'
    case 'boolean':
      return 'boolean'
    case 'timestamptz':
    case 'timestamp':
    case 'date':
    case 'time':
      return 'Date'
    case 'jsonb':
    case 'json':
      return 'Record<string, unknown>'
    case 'bytea':
      return 'Uint8Array'
    default:
      return 'unknown'
  }
}

function columnDefToTs(def: ColumnDef): string {
  const type = typeof def === 'string' ? def : def.type
  const nullable = typeof def === 'object' && def.nullable === true
  return nullable ? `${columnTypeToTs(type)} | null` : columnTypeToTs(type)
}

// ---------------------------------------------------------------------------
// Collect proc metadata from raw definitions
// ---------------------------------------------------------------------------

interface ProcMeta {
  name: string
  tempTables: TempTableDef[]
}

function collectProcs(defs: Awaited<ReturnType<typeof loadRawDefs>>): Map<string, ProcMeta> {
  const procs = new Map<string, ProcMeta>()

  for (const def of defs) {
    if (def._tag === 'Trigger') {
      const proc = def.procedure
      if (!procs.has(proc.name)) {
        procs.set(proc.name, { name: proc.name, tempTables: proc.tempTables })
      }
    } else if (def._tag === 'Procedure') {
      if (!procs.has(def.name)) {
        procs.set(def.name, { name: def.name, tempTables: def.tempTables })
      }
    }
    // RlsEnable / Policy have no temp tables — skip
  }

  return procs
}

// ---------------------------------------------------------------------------
// Generate TypeScript file content
// ---------------------------------------------------------------------------

function generateFile(procs: Map<string, ProcMeta>, dbImport: string): string {
  const lines: string[] = [
    '// AUTO-GENERATED by kysely-pg-procedures proc:codegen',
    '// DO NOT EDIT — run npm run proc:codegen to regenerate',
    '',
    dbImport,
    '',
  ]

  const ifaceNames: string[] = []

  for (const { name: procName, tempTables } of procs.values()) {
    const ifaceName = procNameToTypeName(procName)
    ifaceNames.push(ifaceName)

    // Use type alias (not interface) so it satisfies Record<string, Record<string, unknown>>
    // in the withProcDB<TMap> constraint. Interfaces don't implicitly satisfy index signatures.
    const tableEntries: string[] = []
    for (const table of tempTables) {
      const cols = [
        `    readonly _proc_instance_id: string`,
        ...Object.entries(table.columns).map(([col, def]) => `    readonly ${col}: ${columnDefToTs(def)}`),
      ]
      tableEntries.push(`  ${table.name}: {\n${cols.join('\n')}\n  }`)
    }

    if (tableEntries.length === 0) {
      lines.push(`export type ${ifaceName} = DB`)
    } else {
      lines.push(`export type ${ifaceName} = DB & {`)
      lines.push(tableEntries.join('\n'))
      lines.push(`}`)
    }
    lines.push('')
  }

  if (ifaceNames.length === 0) {
    lines.push('/** No procedures with temp tables found. */')
    lines.push('export type DBProc = DB')
    lines.push('export type ProcDBMap = Record<string, DB>')
    return lines.join('\n')
  }

  lines.push(
    '/** Union of all per-procedure extended DB types. */',
  )
  lines.push(`export type DBProc = ${ifaceNames.join(' | ')}`)
  lines.push('')

  lines.push(
    '/**',
    ' * Maps procedure names to their extended DB type.',
    ' * Pass to withProcDB<ProcDBMap>() to get typed factory functions.',
    ' *',
    ' * @example',
    " * import { withProcDB } from 'kysely-pg-procedures'",
    " * import type { ProcDBMap } from './db-proc.generated'",
    ' * const { defineRowProcedure, defineRowTrigger } = withProcDB<ProcDBMap>()',
    ' */',
  )
  lines.push('export type ProcDBMap = {')
  for (const { name: procName } of procs.values()) {
    lines.push(`  '${procName}': ${procNameToTypeName(procName)}`)
  }
  lines.push('}')

  return lines.join('\n')
}

// ---------------------------------------------------------------------------
// runCodegen
// ---------------------------------------------------------------------------

export async function runCodegen(config: ProcConfig, cwd: string): Promise<void> {
  if (!config.codegen) {
    throw new Error(
      'proc:codegen requires a `codegen` section in kysely-procedures.config.ts.\n' +
        'Add: codegen: { dbImport: "import type { Database as DB } from \'./generated/database.js\'", output: \'src/db-proc.generated.ts\' }',
    )
  }

  const defs = await loadRawDefs(config.procedures, cwd)
  const procs = collectProcs(defs)

  const content = generateFile(procs, config.codegen.dbImport)

  const outputPath = resolve(cwd, config.codegen.output)
  mkdirSync(dirname(outputPath), { recursive: true })
  writeFileSync(outputPath, content + '\n', 'utf8')

  const procList = [...procs.keys()]
  console.log(`proc:codegen — generated ${relative(cwd, outputPath)}`)
  if (procList.length === 0) {
    console.log('  No procedure definitions found.')
  } else {
    console.log(`  ${procList.length} procedure(s): ${procList.join(', ')}`)
    for (const { name, tempTables } of procs.values()) {
      if (tempTables.length > 0) {
        console.log(`    ${name}: ${tempTables.map((t) => t.name).join(', ')}`)
      }
    }
  }
}
