export interface KppBlock {
  name: string
  kind: 'function' | 'trigger' | 'rls-enable' | 'rls-policy'
  hash: string
  content: string
  migrationFile: string
}

export interface KppDownBlock {
  name: string
  content: string
  migrationFile: string
}

export interface ManifestEntry {
  kind: 'function' | 'trigger' | 'rls-enable' | 'rls-policy'
  hash: string
  lastChanged: string
  migrationFile: string
  conflict: boolean
  conflictingFiles?: string[]
}

export interface Manifest {
  rebuiltAt: string
  rebuiltFrom: 'migration-files'
  entries: Record<string, ManifestEntry>
}

export interface CodegenConfig {
  /**
   * Full import statement for the base DB type generated by kysely-codegen.
   * @example "import type { Database as DB } from './generated/database.js'"
   */
  dbImport: string
  /**
   * Output path for the generated file (relative to CWD).
   * @example 'src/db-proc.generated.ts'
   */
  output: string
}

export interface ProcConfig {
  procedures: string[]
  manifest: string
  migrations: string
  /** Optional codegen configuration for `proc:codegen`. */
  codegen?: CodegenConfig
}

export interface CompiledDef {
  name: string
  kind: 'function' | 'trigger' | 'rls-enable' | 'rls-policy'
  sql: string
  hash: string
}

export interface StatusEntry {
  name: string
  kind: 'function' | 'trigger' | 'rls-enable' | 'rls-policy'
  status: 'unchanged' | 'modified' | 'not-migrated' | 'orphan' | 'tampered' | 'conflict'
  sourceHash?: string
  manifestHash?: string
  migrationFile?: string
  conflictingFiles?: string[]
}
