// AUTO-GENERATED by kysely-pg-procedures proc:codegen
// DO NOT EDIT — run npm run proc:codegen to regenerate

type DB = { playground_items: { id: string; label: string; score: number | null; audit_flag: boolean } }

export type DBProcPlaygroundScoreProc = DB

export type DBProcPlaygroundAuditProc = DB & {
  playground_modified_items: {
    readonly _proc_instance_id: string
    readonly itemId: string
    readonly oldScore: number | null
    readonly newScore: number | null
  }
}

/** Union of all per-procedure extended DB types. */
export type DBProc = DBProcPlaygroundScoreProc | DBProcPlaygroundAuditProc

/**
 * Maps procedure names to their extended DB type.
 * Pass to withProcDB<ProcDBMap>() to get typed factory functions.
 *
 * @example
 * import { withProcDB } from 'kysely-pg-procedures'
 * import type { ProcDBMap } from './db-proc.generated'
 * const { defineRowProcedure, defineRowTrigger } = withProcDB<ProcDBMap>()
 */
export type ProcDBMap = {
  'playground_score_proc': DBProcPlaygroundScoreProc
  'playground_audit_proc': DBProcPlaygroundAuditProc
}
