import { sql } from './sql.js'
import { buildDbContext, makeTypedRowRef } from './db-context.js'
import type { DbContext, TypedRowRef } from './db-context.js'
import type { TempTableAliasMap } from './tempTable.js'
import type { TempTableDef, VarDecls, TriggerEvent, TriggerTiming, SqlFragment } from './types.js'
import {
  defineProcedure,
  defineTrigger,
  makeRowBodyCallback,
  type ProcedureDefinition,
  type TriggerDefinition,
  type ProcedureOptions,
  type RowBodyContext,
  type WithTransitionTables,
} from './procedure.js'

// ---------------------------------------------------------------------------
// withProcDB
// ---------------------------------------------------------------------------

/**
 * Create procedure factory functions pre-bound to a `ProcDBMap` generated by
 * `proc:codegen`. The procedure name acts as a discriminant to select the
 * correct per-proc extended DB type from the map.
 *
 * Without codegen, use the standalone factories directly:
 *   `defineRowTrigger<DB>()`, `defineRowProcedure<DB>()`, `defineStatementTrigger<DB>()`
 *
 * With codegen:
 * ```ts
 * import { withProcDB } from 'kysely-pg-procedures'
 * import type { ProcDBMap } from './db-proc.generated'
 *
 * const { defineRowProcedure, defineRowTrigger, defineStatementTrigger } = withProcDB<ProcDBMap>()
 *
 * const proc = defineRowProcedure('items', { name: 'my_audit_proc', ... }, ...)
 * // body: DbContext<ProcDBMap['my_audit_proc'], ...>
 * //       → db.selectFrom('MyTempTable') is fully type-checked ✓
 * ```
 */
/**
 * Extracts TMap[TName] and asserts it satisfies Record<string, Record<string, unknown>>.
 * Used to bridge the constraint gap: TMap's value type is Record<string, unknown>,
 * but DbContext needs Record<string, Record<string, unknown>> (the actual DB shape).
 * At the call site with a concrete ProcDBMap, TypeScript resolves this to the
 * specific per-proc extended DB type.
 */
type ProcDB<TMap, TName extends keyof TMap> =
  TMap[TName] extends Record<string, Record<string, unknown>>
    ? TMap[TName]
    : never

export function withProcDB<
  TMap extends Record<string, Record<string, unknown>>,
>() {
  return {
    /**
     * Define a row procedure typed against `TMap[options.name]`.
     * Add `events` to constrain NEW/OLD availability (INSERT/UPDATE → NEW,
     * UPDATE/DELETE → OLD). Without events, both are always available.
     */
    defineRowProcedure<
      TName extends keyof TMap & string,
      TTable extends keyof ProcDB<TMap, TName> & string,
      TTables extends TempTableDef[] = [],
    >(
      table: TTable,
      options: ProcedureOptions & { name: TName },
      tempTables: TTables,
      vars: VarDecls,
      body: (ctx: RowBodyContext<ProcDB<TMap, TName>[TTable], ProcDB<TMap, TName>, TTables>) => void,
    ): ProcedureDefinition {
      return defineProcedure<ProcDB<TMap, TName>, TTables>(
        options,
        tempTables,
        vars,
        makeRowBodyCallback(body, makeTypedRowRef<ProcDB<TMap, TName>[TTable]>('NEW'), makeTypedRowRef<ProcDB<TMap, TName>[TTable]>('OLD')),
      )
    },

    /**
     * Define a FOR EACH ROW trigger typed against `TMap[options.procedureName]`.
     * With `events: [...] as const`, NEW/OLD availability is narrowed.
     */
    defineRowTrigger<
      TName extends keyof TMap & string,
      TTable extends keyof ProcDB<TMap, TName> & string,
      TTables extends TempTableDef[] = [],
      const TEvents extends readonly TriggerEvent[] = readonly TriggerEvent[],
    >(
      table: TTable,
      options: {
        name: string
        procedureName: TName
        timing: TriggerTiming
        events: TEvents
        when?: SqlFragment
        columns?: string[]
      },
      tempTables: TTables,
      vars: VarDecls,
      body: (ctx: RowBodyContext<ProcDB<TMap, TName>[TTable], ProcDB<TMap, TName>, TTables>) => void,
    ): TriggerDefinition {
      const proc = defineProcedure<ProcDB<TMap, TName>, TTables>(
        { name: options.procedureName },
        tempTables,
        vars,
        makeRowBodyCallback(body, makeTypedRowRef<ProcDB<TMap, TName>[TTable]>('NEW'), makeTypedRowRef<ProcDB<TMap, TName>[TTable]>('OLD')),
      )
      return defineTrigger(
        {
          name: options.name,
          table: table as string,
          timing: options.timing,
          events: [...options.events] as TriggerEvent[],
          forEach: 'ROW',
          when: options.when,
          columns: options.columns,
        },
        proc,
      )
    },

    /**
     * Define a FOR EACH STATEMENT trigger typed against `TMap[options.procedureName]`.
     * The `referencing` aliases are inferred as literal types so
     * `db.selectFrom('inserted')` / `db.selectFrom('removed')` are type-checked.
     */
    defineStatementTrigger<
      TName extends keyof TMap & string,
      TTable extends keyof ProcDB<TMap, TName> & string,
      TTables extends TempTableDef[] = [],
      TRefNew extends string = never,
      TRefOld extends string = never,
    >(
      table: TTable,
      options: {
        name: string
        procedureName: TName
        timing: TriggerTiming
        events: TriggerEvent[]
        referencing?: { new?: TRefNew; old?: TRefOld }
        when?: SqlFragment
      },
      tempTables: TTables,
      vars: VarDecls,
      body: (ctx: {
        sql: typeof sql
        db: DbContext<
          WithTransitionTables<ProcDB<TMap, TName>, TTable, TRefNew, TRefOld>,
          TTables,
          TempTableAliasMap<TTables>
        >
      }) => void,
    ): TriggerDefinition {
      const proc = defineProcedure<
        WithTransitionTables<ProcDB<TMap, TName>, TTable, TRefNew, TRefOld>,
        TTables
      >(
        { name: options.procedureName },
        tempTables,
        vars,
        body,
      )
      return defineTrigger(
        {
          name: options.name,
          table: table as string,
          timing: options.timing,
          events: options.events,
          forEach: 'STATEMENT',
          referencing: options.referencing
            ? { old: options.referencing.old, new: options.referencing.new }
            : undefined,
          when: options.when,
        },
        proc,
      )
    },
  }
}
